apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-config
  namespace: flight-telemetry
data:
  HTTP_PORT: "3000"
  TCP_PORT: "9000"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
  ELASTICSEARCH_INDEX: "telemetry"
  SPACECRAFT_ID: "DEMO-SAT-01"
  INTERVAL_MS: "1000"
